#!/bin/bash

touch list.txt
touch got.txt

if [ $(( ( RANDOM % 10 )  + 1 )) -gt 3 ] ; then
echo "No Pokemon here"
exit 0
fi

pokemon=$(shuf -n 1 list.txt)
echo "You found a Pokemon!"
echo "It's a $pokemon"
grep "$pokemon" got.txt &>/dev/null && echo "But you already have a $pokemon" && exit 0 || read -p "Do you want to keep it? (Y/n) " add

case $add in
y|Y)
echo "$pokemon" >> got.txt
echo "Added"
;;
*)
echo "Thrown away :("
;;
esac
